DROP ROLE IF EXISTS nciapp;

CREATE ROLE nciapp LOGIN
  PASSWORD 'nci4everyone'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

DROP DATABASE IF EXISTS ncicore;

CREATE DATABASE ncicore
  WITH OWNER = nciapp
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE ncicore TO nciapp;
